alias: KinderLight Auto Control with Sunset/Sunrise
description: "KinderLight turns on at sunset, off at sunrise, or based on ambient light lux levels"
trigger:
  # Trigger when sun sets (below horizon)
  - platform: state
    entity_id: sun.sun
    to: below_horizon
    id: "night"

  # Trigger when sun rises (above horizon)
  - platform: state
    entity_id: sun.sun
    to: above_horizon
    id: "day"

  # Trigger when ambient light falls below threshold (lux < 30)
  - platform: numeric_state
    entity_id: sensor.ambient_light_lux
    below: 30
    id: "dark"

  # Trigger when ambient light rises above threshold (lux > 50)
  - platform: numeric_state
    entity_id: sensor.ambient_light_lux
    above: 50
    id: "bright"

condition: []

variables:
  # Variables to dynamically capture current color and brightness settings
  kinderlight_color: "{{ state_attr('light.kinderlight_rgb', 'rgb_color') or [255, 160, 80] }}"
  kinderlight_brightness: "{{ state_attr('light.kinderlight_rgb', 'brightness') or 80 }}"
  sun_state: "{{ states('sun.sun') }}"

action:
  - choose:
      # Action block: If sun has set
      - conditions:
          - condition: trigger
            id: "night"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.kinderlight_rgb
            data:
              brightness: "{{ kinderlight_brightness }}"
              rgb_color: "{{ kinderlight_color }}"
              transition: 2.0  # Fade in over 2 seconds

      # Action block: If sun has risen
      - conditions:
          - condition: trigger
            id: "day"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.kinderlight_rgb
            data:
              transition: 2.0  # Fade out over 2 seconds

      # Action block: If light level low and it is daytime
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ sun_state == 'above_horizon' }}"
              - condition: trigger
                id: "dark"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.kinderlight_rgb
            data:
              brightness: "{{ kinderlight_brightness }}"
              rgb_color: "{{ kinderlight_color }}"
              transition: 2.0

      # Action block: If light level high and it is daytime
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ sun_state == 'above_horizon' }}"
              - condition: trigger
                id: "bright"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.kinderlight_rgb
            data:
              transition: 2.0

mode: single
