# KinderLight Home Assistant Package
# License: GPL-3.0

homeassistant:
  name: KinderLight Package

esphome:
  name: kinderlight

# Light entity
light:
  - platform: rgb
    name: "KinderLight RGB"
    red: output_red
    green: output_green
    blue: output_blue
    effects:
      - random:
      - strobe:
      - flicker:

# Ambient light sensor
sensor:
  - platform: bh1750
    name: "Ambient Light Lux"
    address: 0x23
    update_interval: 30s

# Output pins
output:
  - platform: ledc
    pin: GPIO14
    id: output_red
  - platform: ledc
    pin: GPIO27
    id: output_green
  - platform: ledc
    pin: GPIO26
    id: output_blue

# Automation
automation:
  - alias: KinderLight Auto Control
    description: "KinderLight turns on at sunset, off at sunrise, or based on ambient light lux"
    trigger:
      - platform: state
        entity_id: sun.sun
        to: below_horizon
        id: "night"

      - platform: state
        entity_id: sun.sun
        to: above_horizon
        id: "day"

      - platform: numeric_state
        entity_id: sensor.ambient_light_lux
        below: 30
        id: "dark"

      - platform: numeric_state
        entity_id: sensor.ambient_light_lux
        above: 50
        id: "bright"

    condition: []

    variables:
      kinderlight_color: "{{ state_attr('light.kinderlight_rgb', 'rgb_color') or [255, 160, 80] }}"
      kinderlight_brightness: "{{ state_attr('light.kinderlight_rgb', 'brightness') or 80 }}"
      sun_state: "{{ states('sun.sun') }}"

    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "night"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.kinderlight_rgb
                data:
                  brightness: "{{ kinderlight_brightness }}"
                  rgb_color: "{{ kinderlight_color }}"
                  transition: 2.0

          - conditions:
              - condition: trigger
                id: "day"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.kinderlight_rgb
                data:
                  transition: 2.0

          - conditions:
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ sun_state == 'above_horizon' }}"
                  - condition: trigger
                    id: "dark"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.kinderlight_rgb
                data:
                  brightness: "{{ kinderlight_brightness }}"
                  rgb_color: "{{ kinderlight_color }}"
                  transition: 2.0

          - conditions:
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ sun_state == 'above_horizon' }}"
                  - condition: trigger
                    id: "bright"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.kinderlight_rgb
                data:
                  transition: 2.0

    mode: single
