esphome:
  name: kinderlight_rgb
  friendly_name: KinderLight RGB

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging via UART
logger:

# default HA integration, OTA updater and backup http web portal
api:
  # password: !secret device_password
#  encryption:
#    key: "YOUR_ENCRYPTION_KEY"
ota:
  # password: !secret device_password
wifi:
  # Read the wifi/pass from secrets.yaml:
  # wifi_ssid: "My Wifi XX"
  # wifi_password: "XXXXXXX"
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Web server for local diagnostics
web_server:
  port: 80

# https://esphome.io/components/captive_portal.html
#captive_portal:

# I2C Bus for BH1750 sensor
i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  id: bus_a

# Ambient light sensor
sensor:
  - platform: bh1750
    name: "KinderLight Ambient Light"
    id: ambient_light
    address: 0x23
    update_interval: 30s

# PWM outputs for RGB LED
output:
  - platform: ledc
    id: pwm_red
    pin: GPIO1
    frequency: 1000Hz
  - platform: ledc
    id: pwm_green
    pin: GPIO2
    frequency: 1000Hz
  - platform: ledc
    id: pwm_blue
    pin: GPIO3
    frequency: 1000Hz

# RGB Light entity
light:
  - platform: rgb
    name: "KinderLight RGB"
    red: pwm_red
    green: pwm_green
    blue: pwm_blue
    id: kinderlight_rgb_light
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 1s
    effects:
      - strobe: # to identify the object
    effects:
      - pulse:
          name: "Night Fade"
          transition_length: 2s
          update_interval: 3s
          min_brightness: 10%
          max_brightness: 70%

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "KinderLight IP Address"

# Binary sensor to detect darkness
binary_sensor:
  - platform: template
    name: "KinderLight Is Dark"
    id: is_dark
    lambda: |-
      if (id(ambient_light).state < 50) {
        return true;
      } else {
        return false;
      }
    device_class: light

interval:
  - interval: 10s
    then:
      - if:
          condition:
            binary_sensor.is_on: is_dark
          then:
            - light.turn_on:
                id: kinderlight_rgb_light
                brightness: 64
          else:
            - light.turn_off: kinderlight_rgb_light

# (Optional) Voltage input monitoring
# If you connect battery or input voltage monitoring
# Uncomment below if needed
#  - platform: adc
#    pin: GPIO36
#    name: "Input Voltage"
#    attenuation: 11db
interval:
  - interval: 60s
    then:
      - lambda: |-
          if (!id(bh1750_sensor).has_state()) {
            ESP_LOGW("i2c", "BH1750 sensor missing or not responding.");
          }
text_sensor:
  - platform: version
    name: "KinderLight ESPHome Version"
    icon: mdi:information
    hide_timestamp: true
