esphome:
  name: kinderlight
  comment: "ESP32 RGB Nightlight with BH1750"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "KinderLight Fallback"
    password: "fallbackpass"

captive_portal:

# Enable I2C for BH1750
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

sensor:
  - platform: bh1750
    name: "Ambient Light Lux"
    address: 0x23
    update_interval: 30s

output:
  - platform: ledc
    id: pwm_red
    pin: GPIO14
    frequency: 1000 Hz

  - platform: ledc
    id: pwm_green
    pin: GPIO27
    frequency: 1000 Hz

  - platform: ledc
    id: pwm_blue
    pin: GPIO26
    frequency: 1000 Hz

light:
  <<: !include nightlight_effect.yaml

text_sensor:
  - <<: !include firmware_version.yaml

light:
  - platform: rgb
    name: "KinderLight RGB"
    red: pwm_red
    green: pwm_green
    blue: pwm_blue
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 1s
    effects:
      - random:
      - strobe:
      - flicker:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "KinderLight IP Address"
